import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { connectToDatabase } from "@/lib/mongodb";
import { UserModel, ProfileModel } from "@/lib/models";
import { generateProfileId } from "@/lib/profileIdGenerator";

const SEED_PASSWORD = "Seed@1234";

const GROOMERS = [
  {
    name: "Ligin Arul Justus",
    email: "ligin.seed@regin.dev",
    phone: "9876500000",
    religion: "CHRISTIAN" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "MALE" as const,
      age: 27,
      dateOfBirth: new Date("1998-05-10"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Chennai",
      address: "15, Besant Nagar, Chennai - 600090",
      location: "Chennai",
      caste: "Roman Catholic",
      subCaste: "Vellalar",
      religion: "CHRISTIAN",
      education: "B.E. Computer Science",
      currentJob: "Software Developer",
      monthlyIncome: 70000,
      height: 173,
      weight: 70,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Chennai",
      timeOfBirth: "10:30",
      rashi: "Mithuna",
      nakshatra: "Thiruvathirai",
      lagnam: "Simha",
      fatherName: "Justus Arockiaraj",
      fatherOccupation: "Business",
      motherName: "Arul Mary Justus",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 0,
      totalSisters: 1,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Justus Arockiaraj",
      contactNumber: "+919876500000",
      whatsappNo: "+919876500000",
      expectations: "Looking for a well-educated, God-fearing Christian girl. Should be family-oriented and caring.",
      income: 70000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Karthik Rajan",
    email: "karthik.seed@regin.dev",
    phone: "9876543210",
    religion: "HINDU" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "MALE" as const,
      age: 28,
      dateOfBirth: new Date("1997-04-15"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Chennai",
      address: "12, Anna Nagar, Chennai - 600040",
      location: "Chennai",
      caste: "Mudaliar",
      subCaste: "Senguntha Mudaliar",
      religion: "HINDU",
      education: "B.E. Computer Science",
      currentJob: "Software Engineer",
      monthlyIncome: 65000,
      height: 172,
      weight: 68,
      complexion: "WHEATISH",
      motherTongue: "Tamil",
      placeOfBirth: "Chennai",
      timeOfBirth: "08:30",
      rashi: "Mithuna",
      nakshatra: "Thiruvathirai",
      lagnam: "Kanya",
      fatherName: "Rajan Murugesan",
      fatherOccupation: "Retired Government Employee",
      motherName: "Selvi Rajan",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 0,
      totalSisters: 1,
      marriedSisters: 1,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Rajan Murugesan",
      contactNumber: "+919876543210",
      whatsappNo: "+919876543210",
      expectations: "Looking for a well-educated, family-oriented girl from a good family. Caste no bar.",
      income: 65000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Suresh Kumar",
    email: "suresh.seed@regin.dev",
    phone: "9865432109",
    religion: "HINDU" as const,
    familyClass: "UC" as const,
    profile: {
      gender: "MALE" as const,
      age: 30,
      dateOfBirth: new Date("1995-11-22"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Coimbatore",
      address: "45, Saibaba Colony, Coimbatore - 641011",
      location: "Coimbatore",
      caste: "Gounder",
      subCaste: "Kongu Vellala Gounder",
      religion: "HINDU",
      education: "M.Tech Information Technology",
      currentJob: "Senior Developer",
      monthlyIncome: 95000,
      height: 175,
      weight: 72,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Coimbatore",
      timeOfBirth: "14:15",
      rashi: "Rishabam",
      nakshatra: "Krithigai",
      lagnam: "Simha",
      fatherName: "Kumar Gounder",
      fatherOccupation: "Farmer & Business",
      motherName: "Kavitha Kumar",
      motherOccupation: "Homemaker",
      totalBrothers: 2,
      marriedBrothers: 1,
      totalSisters: 0,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "UC" as const,
      contactPersonName: "Kumar Gounder",
      contactNumber: "+919865432109",
      whatsappNo: "+919865432109",
      expectations: "Seeking a well-educated Gounder girl from a respectable family. Should be understanding and supportive.",
      income: 95000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Arun Selvam",
    email: "arun.seed@regin.dev",
    phone: "9754321098",
    religion: "HINDU" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "MALE" as const,
      age: 25,
      dateOfBirth: new Date("2000-07-08"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Madurai",
      address: "78, KK Nagar, Madurai - 625020",
      location: "Madurai",
      caste: "Nadar",
      subCaste: "Sanar",
      religion: "HINDU",
      education: "B.Sc Computer Science",
      currentJob: "IT Support Engineer",
      monthlyIncome: 35000,
      height: 168,
      weight: 62,
      complexion: "WHEATISH",
      motherTongue: "Tamil",
      placeOfBirth: "Madurai",
      timeOfBirth: "06:00",
      rashi: "Kadagam",
      nakshatra: "Punarpusam",
      lagnam: "Meenam",
      fatherName: "Selvam Nadar",
      fatherOccupation: "Shop Owner",
      motherName: "Meena Selvam",
      motherOccupation: "Tailoring",
      totalBrothers: 1,
      marriedBrothers: 1,
      totalSisters: 1,
      marriedSisters: 0,
      houseDetails: "FAMILY",
      familyStatus: "MC" as const,
      contactPersonName: "Selvam Nadar",
      contactNumber: "+919754321098",
      whatsappNo: "+919754321098",
      expectations: "Looking for an educated, caring girl. Should be respectful to elders.",
      income: 35000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Mohamed Farooq",
    email: "farooq.seed@regin.dev",
    phone: "9643210987",
    religion: "MUSLIM" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "MALE" as const,
      age: 27,
      dateOfBirth: new Date("1998-03-12"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Erode",
      address: "23, Market Street, Erode - 638001",
      location: "Erode",
      caste: "Rowther",
      subCaste: "Labbai",
      religion: "MUSLIM",
      education: "B.Com",
      currentJob: "Business (Textile)",
      monthlyIncome: 55000,
      height: 170,
      weight: 70,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Erode",
      timeOfBirth: "11:45",
      rashi: "Mesham",
      nakshatra: "Ashwini",
      lagnam: "Dhanusu",
      fatherName: "Abdul Farooq",
      fatherOccupation: "Textile Business",
      motherName: "Zubaida Farooq",
      motherOccupation: "Homemaker",
      totalBrothers: 2,
      marriedBrothers: 1,
      totalSisters: 2,
      marriedSisters: 2,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Abdul Farooq",
      contactNumber: "+919643210987",
      whatsappNo: "+919643210987",
      expectations: "Looking for a practising Muslim girl, preferably educated and from a good family.",
      income: 55000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Christopher Daniel",
    email: "chris.seed@regin.dev",
    phone: "9532109876",
    religion: "CHRISTIAN" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "MALE" as const,
      age: 26,
      dateOfBirth: new Date("1999-12-25"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Salem",
      address: "5, Church Road, Salem - 636007",
      location: "Salem",
      caste: "Roman Catholic",
      subCaste: "Vellalar",
      religion: "CHRISTIAN",
      education: "MBA Finance",
      currentJob: "Bank Manager",
      monthlyIncome: 75000,
      height: 174,
      weight: 73,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Salem",
      timeOfBirth: "09:20",
      rashi: "Makaram",
      nakshatra: "Thiruvonam",
      lagnam: "Thulam",
      fatherName: "Daniel Arockiam",
      fatherOccupation: "Retired Teacher",
      motherName: "Mary Daniel",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 0,
      totalSisters: 2,
      marriedSisters: 1,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Daniel Arockiam",
      contactNumber: "+919532109876",
      whatsappNo: "+919532109876",
      expectations: "Seeking a Christian girl, educated and God-fearing. Caste no bar.",
      income: 75000,
      physicallyChallenge: false,
    },
  },
];

const BRIDES = [
  {
    name: "Priya Devi",
    email: "priya.seed@regin.dev",
    phone: "9421098765",
    religion: "HINDU" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "FEMALE" as const,
      age: 24,
      dateOfBirth: new Date("2001-06-18"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Chennai",
      address: "34, Velachery Main Road, Chennai - 600042",
      location: "Chennai",
      caste: "Mudaliar",
      subCaste: "Senguntha Mudaliar",
      religion: "HINDU",
      education: "B.Sc Nursing",
      currentJob: "Staff Nurse",
      monthlyIncome: 32000,
      height: 160,
      weight: 52,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Chennai",
      timeOfBirth: "07:10",
      rashi: "Mithuna",
      nakshatra: "Mrugasheersham",
      lagnam: "Simha",
      fatherName: "Devi Murugan",
      fatherOccupation: "Government Employee",
      motherName: "Usha Devi",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 0,
      totalSisters: 0,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Devi Murugan",
      contactNumber: "+919421098765",
      whatsappNo: "+919421098765",
      expectations: "Looking for a well-settled, caring, and educated groom. Should be working professional.",
      income: 32000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Kavitha Raj",
    email: "kavitha.seed@regin.dev",
    phone: "9310987654",
    religion: "HINDU" as const,
    familyClass: "UC" as const,
    profile: {
      gender: "FEMALE" as const,
      age: 22,
      dateOfBirth: new Date("2003-02-14"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Coimbatore",
      address: "88, RS Puram, Coimbatore - 641002",
      location: "Coimbatore",
      caste: "Gounder",
      subCaste: "Kongu Vellala Gounder",
      religion: "HINDU",
      education: "B.Ed",
      currentJob: "Primary School Teacher",
      monthlyIncome: 28000,
      height: 157,
      weight: 50,
      complexion: "VERY_FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Coimbatore",
      timeOfBirth: "16:30",
      rashi: "Kanni",
      nakshatra: "Hastham",
      lagnam: "Rishabam",
      fatherName: "Raj Gounder",
      fatherOccupation: "Agricultural Land Owner",
      motherName: "Shanthi Raj",
      motherOccupation: "Homemaker",
      totalBrothers: 2,
      marriedBrothers: 0,
      totalSisters: 1,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "UC" as const,
      contactPersonName: "Raj Gounder",
      contactNumber: "+919310987654",
      whatsappNo: "+919310987654",
      expectations: "Looking for a Gounder groom, educated and from a good family. Should be understanding.",
      income: 28000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Lakshmi Sundaram",
    email: "lakshmi.seed@regin.dev",
    phone: "9209876543",
    religion: "HINDU" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "FEMALE" as const,
      age: 25,
      dateOfBirth: new Date("2000-09-05"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Tiruchirappalli",
      address: "12, Srirangam Road, Trichy - 620006",
      location: "Tiruchirappalli",
      caste: "Chettiar",
      subCaste: "Nattukotai Chettiar",
      religion: "HINDU",
      education: "B.E. Electronics",
      currentJob: "Software Engineer",
      monthlyIncome: 58000,
      height: 162,
      weight: 55,
      complexion: "WHEATISH",
      motherTongue: "Tamil",
      placeOfBirth: "Trichy",
      timeOfBirth: "12:00",
      rashi: "Thulam",
      nakshatra: "Swathi",
      lagnam: "Katakam",
      fatherName: "Sundaram Chettiar",
      fatherOccupation: "Business",
      motherName: "Malathi Sundaram",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 1,
      totalSisters: 1,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Sundaram Chettiar",
      contactNumber: "+919209876543",
      whatsappNo: "+919209876543",
      expectations: "Seeking an IT professional groom, preferably from Tamil Nadu. Good family values important.",
      income: 58000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Fathima Begum",
    email: "fathima.seed@regin.dev",
    phone: "9098765432",
    religion: "MUSLIM" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "FEMALE" as const,
      age: 23,
      dateOfBirth: new Date("2002-01-30"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Erode",
      address: "56, Brough Road, Erode - 638001",
      location: "Erode",
      caste: "Rowther",
      subCaste: "Labbai",
      religion: "MUSLIM",
      education: "MBBS",
      currentJob: "Junior Doctor",
      monthlyIncome: 45000,
      height: 158,
      weight: 53,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Erode",
      timeOfBirth: "05:30",
      rashi: "Meenam",
      nakshatra: "Revathi",
      lagnam: "Kanni",
      fatherName: "Ibrahim Begum",
      fatherOccupation: "Business",
      motherName: "Razeena Ibrahim",
      motherOccupation: "Homemaker",
      totalBrothers: 2,
      marriedBrothers: 1,
      totalSisters: 1,
      marriedSisters: 0,
      houseDetails: "OWN",
      familyStatus: "MC" as const,
      contactPersonName: "Ibrahim Begum",
      contactNumber: "+919098765432",
      whatsappNo: "+919098765432",
      expectations: "Seeking a well-educated Muslim groom who is practising and from a good family.",
      income: 45000,
      physicallyChallenge: false,
    },
  },
  {
    name: "Mary Anugraha",
    email: "mary.seed@regin.dev",
    phone: "8987654321",
    religion: "CHRISTIAN" as const,
    familyClass: "MC" as const,
    profile: {
      gender: "FEMALE" as const,
      age: 24,
      dateOfBirth: new Date("2001-08-10"),
      maritalStatus: "SINGLE",
      nativeDistrict: "Vellore",
      address: "9, Hospital Road, Vellore - 632004",
      location: "Vellore",
      caste: "Roman Catholic",
      subCaste: "Vellalar",
      religion: "CHRISTIAN",
      education: "MBA HR",
      currentJob: "HR Executive",
      monthlyIncome: 38000,
      height: 163,
      weight: 56,
      complexion: "FAIR",
      motherTongue: "Tamil",
      placeOfBirth: "Vellore",
      timeOfBirth: "10:15",
      rashi: "Simha",
      nakshatra: "Magam",
      lagnam: "Mithuna",
      fatherName: "Arockiam Raj",
      fatherOccupation: "Teacher",
      motherName: "Selvi Arockiam",
      motherOccupation: "Homemaker",
      totalBrothers: 1,
      marriedBrothers: 1,
      totalSisters: 0,
      marriedSisters: 0,
      houseDetails: "RENTED",
      familyStatus: "MC" as const,
      contactPersonName: "Arockiam Raj",
      contactNumber: "+918987654321",
      whatsappNo: "+918987654321",
      expectations: "Looking for a Christian groom who is working and family-oriented. Caste no bar.",
      income: 38000,
      physicallyChallenge: false,
    },
  },
];

const ADMIN_PASSWORD = "Admin@1234";

export async function GET() {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json({ error: "Not available in production" }, { status: 403 });
  }
  await connectToDatabase();

  const passwordHash      = await bcrypt.hash(SEED_PASSWORD, 10);
  const adminPasswordHash = await bcrypt.hash(ADMIN_PASSWORD, 10);
  const results: string[] = [];
  const skipped: string[] = [];

  // ── Seed admin user ────────────────────────────────────────────────────────
  const adminEmail = "admin@test.com";
  const existingAdmin = await UserModel.findOne({ email: adminEmail }).lean();
  if (existingAdmin) {
    skipped.push("admin@test.com (admin)");
  } else {
    await UserModel.create({
      name:               "Admin",
      email:              adminEmail,
      phone:              "0000000000",
      passwordHash:       adminPasswordHash,
      role:               "ADMIN",
      status:             "ACTIVE",
      verificationStatus: "VERIFIED",
    });
    results.push("admin@test.com → ADMIN");
  }

  // ── Seed regular users ─────────────────────────────────────────────────────
  const allSeedUsers = [
    ...GROOMERS.map((g) => ({ ...g, profileType: "GROOM" as const })),
    ...BRIDES.map((b) => ({ ...b, profileType: "BRIDE" as const })),
  ];

  for (const seed of allSeedUsers) {
    const existing = await UserModel.findOne({ email: seed.email }).lean();
    if (existing) {
      skipped.push(seed.name);
      continue;
    }

    const profileId = await generateProfileId(
      seed.profile.gender,
      seed.religion,
      seed.familyClass,
    );

    const user = await UserModel.create({
      name: seed.name,
      email: seed.email,
      phone: seed.phone,
      passwordHash,
      role: "USER",
      profileId,
      profileType: seed.profileType,
      familyClass: seed.familyClass,
      status: "ACTIVE",
      verificationStatus: "VERIFIED",
    });

    await ProfileModel.create({
      userId: user._id,
      profileType: seed.profileType,
      familyClass: seed.familyClass,
      profileStatus: "APPROVED",
      ...seed.profile,
    });

    results.push(`${seed.name} → ${profileId}`);
  }

  return NextResponse.json({
    created: results,
    skipped,
    userPassword:  SEED_PASSWORD,
    adminPassword: ADMIN_PASSWORD,
    note: "Regular users: login with Profile ID. Admin: login with admin@test.com",
  });
}
