export const CASTE_LIST: readonly string[] = [
  // ── Brahmin ─────────────────────────────────────────────────────────────────
  "Brahmin - Iyer",
  "Brahmin - Iyengar",
  "Brahmin - Smartha",
  "Brahmin - Sri Vaishnava",
  "Brahmin - Gurukkal",
  "Brahmin - Namboodiri",
  "Brahmin - Madhva",
  "Brahmin - Havyaka",
  "Brahmin - Shivalli",
  "Brahmin - Karhade",
  "Brahmin - Deshastha",
  "Brahmin - Chitpavan",
  "Brahmin - Saraswat",
  "Brahmin - Telugu Brahmin",
  "Brahmin - Others",
  // ── Tamil Nadu OBC ───────────────────────────────────────────────────────────
  "Agamudaiyar",
  "Ambalakarar",
  "Arcot Mudaliar",
  "Asari / Vishwakarma",
  "Balija Naidu",
  "Boyar",
  "Chettiar",
  "Devanga",
  "Dheevara / Meenavar",
  "Gounder",
  "Kaikolar / Sengunthar",
  "Kallar",
  "Kamma Naidu",
  "Kapu / Telaga",
  "Karkatta Mudaliar",
  "Konar / Yadav",
  "Kongu Vellala Gounder",
  "Kusavar / Kuyavar",
  "Mannan",
  "Maravar",
  "Meenavar / Pattanavar",
  "Mudaliar",
  "Nadar",
  "Naicker",
  "Naidu",
  "Nattukotai Chettiar",
  "Nayakkar",
  "Padaiyachi",
  "Pillai",
  "Saiva Mudaliar",
  "Saiva Pillai",
  "Saliya",
  "Senguntha Mudaliar",
  "Thevar / Mukkulathor",
  "Udayar",
  "Vaniya Chettiar",
  "Vanniyar",
  "Vellalar",
  "Vellala Gounder",
  "Vishwakarma",
  // ── Tamil Nadu SC ────────────────────────────────────────────────────────────
  "Arunthathiyar",
  "Chakkiliyar",
  "Pallar / Devendra Kula Vellalar",
  "Paraiyar",
  "Vannar",
  // ── Tamil Nadu ST ────────────────────────────────────────────────────────────
  "Irula",
  "Kota",
  "Kurumba",
  "Toda",
  // ── Kerala ───────────────────────────────────────────────────────────────────
  "Ezhava",
  "Menon",
  "Nair",
  "Nambiar",
  "Pulaya",
  "Thiyya",
  // ── Karnataka / Andhra ───────────────────────────────────────────────────────
  "Billava",
  "Bunt",
  "Kamma",
  "Kuruba",
  "Lingayat",
  "Mudaliars (Karnataka)",
  "Okkaliga / Vokkaliga",
  "Reddy",
  "Scheduled Caste (Karnataka)",
  "Velama",
  // ── North India ──────────────────────────────────────────────────────────────
  "Ahir / Yadav",
  "Bania",
  "Baniya",
  "Banjara",
  "Brahmin (North)",
  "Chamar",
  "Gujjar",
  "Jat",
  "Kayastha",
  "Kumhar",
  "Kurmi",
  "Lodha",
  "Mali",
  "Maratha",
  "Meena",
  "Patel",
  "Rajput",
  "Sonar",
  "Teli",
  // ── Muslim ───────────────────────────────────────────────────────────────────
  "Muslim - Lebbai",
  "Muslim - Maraikayar",
  "Muslim - Momin / Ansari",
  "Muslim - Pathan",
  "Muslim - Rawther",
  "Muslim - Sheikh",
  "Muslim - Syed",
  "Muslim - Others",
  // ── Christian ────────────────────────────────────────────────────────────────
  "Christian - CSI",
  "Christian - Catholic",
  "Christian - Pentecostal",
  "Christian - Others",
  // ── Others ───────────────────────────────────────────────────────────────────
  "Arya Vysya",
  "Inter-caste",
  "Jain",
  "Sikh",
  "Others / Not Listed",
].sort((a, b) => a.localeCompare(b));

export const SUBCASTE_LIST: readonly string[] = [
  // Brahmin sub-castes
  "Ashtasahasram",
  "Brahacharanam",
  "Gurukkal",
  "Kanchipuram",
  "Madhyandina",
  "Mulakanadu",
  "Pancha Dravida",
  "Thenkalai",
  "Vadakalai",
  "Vadama",
  "Vathima",
  "Venbudi",
  // Mudaliar sub-castes
  "Agamudaiya Mudaliar",
  "Arcot Mudaliar",
  "Isai Vellalar",
  "Kaikolar Mudaliar",
  "Karkatta Mudaliar",
  "Mudali",
  "Mudaliar",
  "Saiva Mudaliar",
  "Senguntha Mudaliar",
  // Gounder sub-castes
  "Kongu Vellala Gounder",
  "Narambu Gounder",
  "Nadar Gounder",
  "Piramalai Kallar",
  "Vellala Gounder",
  "Vettuva Gounder",
  // Pillai sub-castes
  "Agamudaiya Pillai",
  "Karkatta Pillai",
  "Nair Pillai",
  "Saiva Pillai",
  "Sozhiya Vellalar",
  "Vellalar Pillai",
  // Chettiar sub-castes
  "Komati",
  "Nattukotai Chettiar",
  "Ngarathar",
  "Sozhia Chettiar",
  "Vaniya Chettiar",
  // Thevar sub-castes
  "Agamudaiyar",
  "Kallar",
  "Maravar",
  "Mukkulathor",
  // Naidu sub-castes
  "Balija Naidu",
  "Gajula Kapu",
  "Kamma Naidu",
  "Kapu",
  "Telaga",
  "Velama",
  // Other sub-castes
  "Ambalakarar",
  "Asari",
  "Chakkala",
  "Devar",
  "Dheevara",
  "Ezhava",
  "Golla",
  "Konar",
  "Kovalar",
  "Kulalar",
  "Kuravan",
  "Kusavar",
  "Kuyavar",
  "Mannan",
  "Meenavar",
  "Nair",
  "Naicker",
  "Okkaliga",
  "Padaiyachi",
  "Pallan",
  "Parayan",
  "Pattanavar",
  "Saliya",
  "Thatcher",
  "Udayar",
  "Valluvar",
  "Vannar",
  "Veerakodi Vellalar",
  "Vishwakarma",
  "Yadav",
  // Muslim sub-castes
  "Dekkani",
  "Hanafi",
  "Lebbai",
  "Maraikayar",
  "Memon",
  "Momin",
  "Pathan",
  "Rawther",
  "Shafi",
  "Sheikh",
  "Sunni",
  "Syed",
  // Others
  "Inter-caste",
  "Not Applicable",
  "Others",
].sort((a, b) => a.localeCompare(b));
