export const CASTE_LIST: readonly string[] = [
  "Adhaviyar",
  "Adi Andhra",
  "Adi Dravida",
  "Adi Karnataka",
  "Adiyan",
  "Addi Dravida",
  "Agamudayar",
  "Agaram Vellan Chettiar",
  "Ajila",
  "Alavar",
  "Alwar",
  "Ambalakarar",
  "Andipandaram",
  "Ansar",
  "Appanad Kondayam Kottai Maravar",
  "Aranadan",
  "Arayar",
  "Archakarai Vellala",
  "Arunthathiyar",
  "Aryavathi",
  "Asari",
  "Asooy",
  "Asrai",
  "Asthanthra Golla",
  "Attur Kilnad Koravars",
  "Attur Melnad Koravars",
  "Ayira Vaisyar",
  "Ayyanavar",
  "Azhavar",
  "B.C.",
  "Badagar",
  "Baira",
  "Bakuda",
  "Bandi",
  "Barber / Nai",
  "Battu Turkas",
  "Bellara",
  "Bestha",
  "Bharatar",
  "Bhatraju",
  "Billava",
  "Bondil",
  "Boyar",
  "Boyas",
  "Brahmin",
  "C.K.",
  "Chakkala",
  "Chakkiliyan",
  "Chalavadi",
  "Chamar",
  "Chandala",
  "Changyampudi",
  "Chavalakarar",
  "Chekkalar",
  "Cheramar",
  "Cheruman",
  "Chetiar",
  "Chettiar",
  "Chettinad Valayars",
  "Chettu",
  "Chetty",
  "Chowdry",
  "Christian Gramani",
  "Christian Nadar",
  "Christian Shanar",
  "Dabi Koravars",
  "Dasari",
  "Dekkani Muslims",
  "Devagudi Talayaris",
  "Devangar",
  "Devendrakulathan",
  "Deyar",
  "Dhoby",
  "Dilai",
  "Dobba Koravars",
  "Dobbai Korachas",
  "Dom",
  "Domban",
  "Dombara",
  "Dombs",
  "Dommara",
  "Dommars",
  "Donga Dasaris",
  "Donga Boya",
  "Donga Ur. Korachas",
  "Dudekula",
  "Easanattu Kallar",
  "Enadi",
  "Eravallan",
  "Eravallar",
  "Ezhavathy",
  "Ezhuthachar",
  "Ezhuva",
  "Ezhuvar",
  "F.C.",
  "Gandarvakottai Kallars",
  "Gandarvakottai Koravars",
  "Gandharvakottai Kallars",
  "Gandla",
  "Gangavar",
  "Ganika",
  "Gavara",
  "Gavarai",
  "Godagali",
  "Godda",
  "Golla",
  "Gomolu",
  "Gorrela Dodda Boya",
  "Gosargi",
  "Goundel",
  "Gounder",
  "Gowda",
  "Gramani",
  "Gudu Dasaris",
  "Hegde",
  "Holeya",
  "Idaiyar",
  "Idiga",
  "IIaivaniar",
  "Illathar",
  "Illathu Pillaimar",
  "Illuvar",
  "Irular",
  "Isaivellalar",
  "Iyar",
  "Iyengar",
  "Iyer",
  "Jaggali",
  "Jambavanodai",
  "Jambuvanodai",
  "Jambuvulu",
  "Jangam",
  "Jhetty",
  "Jogi",
  "Jogis",
  "Kabbera",
  "Kadaiyan",
  "Kadambram",
  "Kadar",
  "Kaikolar",
  "Kakkalan",
  "Kal Oddars",
  "Kala Koravars",
  "Kaladi",
  "Kaladis",
  "Kalari Kurup",
  "Kalari Panicker",
  "Kalavathila Boyas",
  "Kalingi",
  "Kalinji Dabikoravars",
  "Kalladi",
  "Kallar",
  "Kallar Kula Thondaman",
  "Kalveli Gounder",
  "Kamalar",
  "Kambar",
  "Kammalar",
  "Kammara",
  "Kanakkan",
  "Kani",
  "Kanikaran",
  "Kanikkar",
  "Kanisu",
  "Kaniyala Vellalar",
  "Kaniyan",
  "Kaniyar Panikkar",
  "Kannada Saineegar",
  "Kannadiya Naidu",
  "Kannadiyar",
  "Kanyan",
  "Kappaliyar",
  "Kappiliya",
  "Karimpalan",
  "Karpoora Chettiar",
  "Karuneegar",
  "Kasukkara Chettiar",
  "Katesar Pattamkatti",
  "Kathikarar",
  "Kattunayakan",
  "Kavara",
  "Kavathi",
  "Kavuthiyar",
  "Keeraikarar",
  "Kepmaris",
  "Kerala Mudali",
  "Kharvi",
  "Khatri",
  "Kochu Velan",
  "Kodikalkarar",
  "Koliyan",
  "Konar",
  "Konavar",
  "Konda Kapus",
  "Kondareddis",
  "Kongu Vellalars",
  "Kongu Chettiar",
  "Kongu Vaishnava",
  "Koodan",
  "Koosa",
  "Kootan",
  "Kootappal Kallars",
  "Koppala Velama",
  "Koracha",
  "Koraga",
  "Koravars",
  "Kota",
  "Koteyar",
  "Krishnanvaka",
  "Kudikara Vellalar",
  "Kudiya",
  "Kudumban",
  "Kudumbi",
  "Kuga Vellalar",
  "Kulala",
  "Kunchidiga",
  "Kunnuvar Mannadi",
  "Kuravan",
  "Kurichchan",
  "Kuruhini Chetty",
  "Kurumans",
  "Kurumba",
  "Kurumba Goundar",
  "Kurumbas",
  "Labbais",
  "Lambadi",
  "Latin Catholic Christian Vannar",
  "Latin Catholic Vannar",
  "Latin Catholics",
  "Lingayat (Jangama)",
  "M.B.C.",
  "Madari",
  "Madiga",
  "Maha Malasar",
  "Mahendra / Medara",
  "Mahratta",
  "Maila",
  "Mala",
  "Malai Arayan",
  "Malai Pandaram",
  "Malai Vedan",
  "Malakkuravan",
  "Malasar",
  "Malayakandi",
  "Malayali",
  "Malayamar",
  "Malayar",
  "Male",
  "Mangala",
  "Maniagar",
  "Manigaicar",
  "Mannan",
  "Mapilla",
  "Marakayar",
  "Maravar",
  "Maravars",
  "Maruthuvar",
  "Mavilan",
  "Meenavar",
  "Melakudi",
  "Moger",
  "Mond Golla",
  "Monda Golla",
  "Monda Koravars",
  "Moondrumandai Enbathunalu",
  "Moopanar",
  "Mooppan",
  "Mooppar",
  "Moundadan Chetty",
  "Muchi",
  "Muddim",
  "Mudugar",
  "Muduvan",
  "Mukayar",
  "Mukkulathor",
  "Mukkuvar / Mukayar",
  "Munaliar",
  "Mundala",
  "Muslim / Sayd",
  "Mutharaiyar",
  "Muthuracha",
  "Muthuraja",
  "Muthuvan",
  "Mutlakampatti",
  "Muttiriyar",
  "Nadar",
  "Nagaram",
  "Naidu",
  "Naikkar",
  "Nainar",
  "Nalakeyava",
  "Nanda",
  "Nangudi Vellalar",
  "Nanjil Mudali",
  "Narikoravar (Kuruvikars)",
  "Navithar",
  "Nawalpeta Korachas",
  "Nayadi",
  "Nayar",
  "Nellorepet Oddars",
  "Nil",
  "Nokkar",
  "Nokkars",
  "Nulayar",
  "O.P.S. Vellalar",
  "Odar",
  "Oddars",
  "Odiya",
  "Okkaliga Gowda",
  "Okkaligar",
  "Okkaliya Gowda",
  "Okkaliya-Gowder",
  "Okkaliya-Gowda",
  "Omitted",
  "Oorudaya Gounder",
  "Oottruvalanattu Vellalar",
  "Orudaya Gounder",
  "Others",
  "Ovachar",
  "Padaiachi",
  "Padanna",
  "Padannan",
  "Padayachi",
  "Padaychi",
  "Padmasaliyar",
  "Pagadai",
  "Paidi",
  "Paingam",
  "Paiyur Kotta Vellalar",
  "Pallai",
  "Pallan",
  "Pallayan",
  "Palliyan",
  "Palliyar",
  "Pambada",
  "Pamulu",
  "Panan",
  "Panar",
  "Panchama",
  "Pandiya Vellalar",
  "Panisaivan / Panisivan",
  "Paniyan",
  "Pannadi",
  "Pannayar",
  "Panniandi",
  "Pannirandam Chettiar",
  "Pano",
  "Pantaram",
  "Paraiyan",
  "Paraiyar",
  "Paravan",
  "Paravar",
  "Parayan",
  "Parkavakulam",
  "Parmyiar",
  "Pathiyan",
  "Patnulkarar",
  "Pattariyar",
  "Pattusaliyar",
  "Pedda Boyas",
  "Perike",
  "Perike Balija",
  "Periya Suriyur Kallars",
  "Perumkollar",
  "Pillai",
  "Pillaimor",
  "Piramalai Kallar",
  "Piramalai Kallars",
  "Podikara Vellalar",
  "Pollar",
  "Ponnai Koravars",
  "Pooluva Gounder",
  "Pooluvar",
  "Poraya",
  "PR / SC",
  "Pronopakari",
  "Pulavar",
  "Pulayan",
  "Pulluvan",
  "Pulluvar",
  "Punnan Vettuva Gounder",
  "Pusala",
  "Puthirai Vannan",
  "Raneyar",
  "Reddy",
  "Rowthar",
  "S.C.",
  "Sachiyar",
  "Sadhu Chetty",
  "Sagara",
  "Sakkaraithamadai Koravars",
  "Sakkaravar",
  "Salem Melnad Koravars",
  "Salem Uppu Koravars",
  "Salivagana",
  "Saliyar",
  "Samagara",
  "Samban",
  "Sambavar",
  "Sapari",
  "Saranga Palli Koravars",
  "Sathatha Srivaishnava",
  "Savalakkarar",
  "SC / PL",
  "Schedule Caste",
  "Schtlear",
  "Sedar",
  "Sembanad Maravars",
  "Semman",
  "Senaikudiyar",
  "Senaithalaivar",
  "Sengunthar",
  "Serakula Vellalar",
  "Serva",
  "Servai",
  "Settipalli Koravars",
  "Shanar",
  "Sheik",
  "Sholaga",
  "Sidhanar",
  "Sooramari Oddars",
  "Sourashtra",
  "Sowrstra",
  "Sozha Vellalar",
  "Sozhia Chetty",
  "Sozhia Vellalar",
  "Srisayar",
  "ST",
  "Sundaram Chetty",
  "Surithimar Nathamar",
  "Syed",
  "Telikula",
  "Telugupatty Chetty",
  "Telungapatti Chettis",
  "Thalli Koravars",
  "Thandan",
  "Thevar",
  "Thogamalai Koravars",
  "Thogatta Veerakshatriya",
  "Tholkollar",
  "Tholuva Naicker",
  "Thondaman",
  "Thoraiyar",
  "Thoriyar",
  "Thoti",
  "Thottia Naicker",
  "Thottia Naickers",
  "Thozhu",
  "Thuluva Vellala",
  "Tiruvalluvar",
  "Toda",
  "Ukkirakula Kshatriya Naicker",
  "Umblar",
  "Uppara",
  "Uppillia",
  "Uppukoravars",
  "Urali Gounder",
  "Urali Gounders",
  "Uraly",
  "Urikkara Nayakkar",
  "Uthama Chettiar",
  "Vaduga Ayar",
  "Vaduga Idaiyar",
  "Vadugar",
  "Vaduvarpatti Koravars",
  "Vakkaligar",
  "Valaiyar",
  "Valayars",
  "Vallalam",
  "Vallambar",
  "Vallanattu Chettiar",
  "Vallon",
  "Valluvan",
  "Valmiki",
  "Van Nair",
  "Vania Chettiar",
  "Vaniyar",
  "Vannan",
  "Vannar",
  "Vanniakula Kshatriya",
  "Varaganeri Koravars",
  "Vathiriyan",
  "Vedar",
  "Veduvar",
  "Veerasaiva",
  "Velakatalanair",
  "Velakattalavar",
  "Velalar",
  "Velan",
  "Velar",
  "Vellan Chettiar",
  "Vellar",
  "Veluthodathu Nair",
  "Venganur Adi-Dravidar",
  "Veppur Parayan",
  "Vetalakara Naicker",
  "Vetan",
  "Vetrilaikarar",
  "Vetta Koravars",
  "Vettaikarar",
  "Vettiyan",
  "Vettuva Gounder",
  "Vettuvan",
  "Virakodi Vellala",
  "Viswakarma",
  "Viswakarmala",
  "Vokkaligar",
  "Wayalpad",
  "Wynad Chetty",
  "Yadhava",
  "Yadav",
  "Yavana",
  "Yerukula",
  "Yogeeswarar",
].sort((a, b) => a.localeCompare(b));

export const SUBCASTE_LIST: readonly string[] = [
  "Adhaviyar",
  "Adi Andhra",
  "Adi Dravida",
  "Adi Karnataka",
  "Adiyan",
  "Addi Dravida",
  "Agamudayar",
  "Agaram Vellan Chettiar",
  "Ajila",
  "Alavar",
  "Alwar",
  "Ambalakarar",
  "Andipandaram",
  "Ansar",
  "Appanad Kondayam Kottai Maravar",
  "Aranadan",
  "Arayar",
  "Archakarai Vellala",
  "Arunthathiyar",
  "Aryavathi",
  "Asari",
  "Asooy",
  "Asrai",
  "Asthanthra Golla",
  "Attur Kilnad Koravars",
  "Attur Melnad Koravars",
  "Ayira Vaisyar",
  "Ayyanavar",
  "Azhavar",
  "B.C.",
  "Badagar",
  "Baira",
  "Bakuda",
  "Bandi",
  "Barber / Nai",
  "Battu Turkas",
  "Bellara",
  "Bestha",
  "Bharatar",
  "Bhatraju",
  "Billava",
  "Bondil",
  "Boyar",
  "Boyas",
  "Brahmin",
  "C.K.",
  "Chakkala",
  "Chakkiliyan",
  "Chalavadi",
  "Chamar",
  "Chandala",
  "Changyampudi",
  "Chavalakarar",
  "Chekkalar",
  "Cheramar",
  "Cheruman",
  "Chetiar",
  "Chettiar",
  "Chettinad Valayars",
  "Chettu",
  "Chetty",
  "Chowdry",
  "Christian Gramani",
  "Christian Nadar",
  "Christian Shanar",
  "Dabi Koravars",
  "Dasari",
  "Dekkani Muslims",
  "Devagudi Talayaris",
  "Devangar",
  "Devendrakulathan",
  "Deyar",
  "Dhoby",
  "Dilai",
  "Dobba Koravars",
  "Dobbai Korachas",
  "Dom",
  "Domban",
  "Dombara",
  "Dombs",
  "Dommara",
  "Dommars",
  "Donga Dasaris",
  "Donga Boya",
  "Donga Ur. Korachas",
  "Dudekula",
  "Easanattu Kallar",
  "Enadi",
  "Eravallan",
  "Eravallar",
  "Ezhavathy",
  "Ezhuthachar",
  "Ezhuva",
  "Ezhuvar",
  "F.C.",
  "Gandarvakottai Kallars",
  "Gandarvakottai Koravars",
  "Gandharvakottai Kallars",
  "Gandla",
  "Gangavar",
  "Ganika",
  "Gavara",
  "Gavarai",
  "Godagali",
  "Godda",
  "Golla",
  "Gomolu",
  "Gorrela Dodda Boya",
  "Gosargi",
  "Goundel",
  "Gounder",
  "Gowda",
  "Gramani",
  "Gudu Dasaris",
  "Hegde",
  "Holeya",
  "Idaiyar",
  "Idiga",
  "IIaivaniar",
  "Illathar",
  "Illathu Pillaimar",
  "Illuvar",
  "Irular",
  "Isaivellalar",
  "Iyar",
  "Iyengar",
  "Iyer",
  "Jaggali",
  "Jambavanodai",
  "Jambuvanodai",
  "Jambuvulu",
  "Jangam",
  "Jhetty",
  "Jogi",
  "Jogis",
  "Kabbera",
  "Kadaiyan",
  "Kadambram",
  "Kadar",
  "Kaikolar",
  "Kakkalan",
  "Kal Oddars",
  "Kala Koravars",
  "Kaladi",
  "Kaladis",
  "Kalari Kurup",
  "Kalari Panicker",
  "Kalavathila Boyas",
  "Kalingi",
  "Kalinji Dabikoravars",
  "Kalladi",
  "Kallar",
  "Kallar Kula Thondaman",
  "Kalveli Gounder",
  "Kamalar",
  "Kambar",
  "Kammalar",
  "Kammara",
  "Kanakkan",
  "Kani",
  "Kanikaran",
  "Kanikkar",
  "Kanisu",
  "Kaniyala Vellalar",
  "Kaniyan",
  "Kaniyar Panikkar",
  "Kannada Saineegar",
  "Kannadiya Naidu",
  "Kannadiyar",
  "Kanyan",
  "Kappaliyar",
  "Kappiliya",
  "Karimpalan",
  "Karpoora Chettiar",
  "Karuneegar",
  "Kasukkara Chettiar",
  "Katesar Pattamkatti",
  "Kathikarar",
  "Kattunayakan",
  "Kavara",
  "Kavathi",
  "Kavuthiyar",
  "Keeraikarar",
  "Kepmaris",
  "Kerala Mudali",
  "Kharvi",
  "Khatri",
  "Kochu Velan",
  "Kodikalkarar",
  "Koliyan",
  "Konar",
  "Konavar",
  "Konda Kapus",
  "Kondareddis",
  "Kongu Vellalars",
  "Kongu Chettiar",
  "Kongu Vaishnava",
  "Koodan",
  "Koosa",
  "Kootan",
  "Kootappal Kallars",
  "Koppala Velama",
  "Koracha",
  "Koraga",
  "Koravars",
  "Kota",
  "Koteyar",
  "Krishnanvaka",
  "Kudikara Vellalar",
  "Kudiya",
  "Kudumban",
  "Kudumbi",
  "Kuga Vellalar",
  "Kulala",
  "Kunchidiga",
  "Kunnuvar Mannadi",
  "Kuravan",
  "Kurichchan",
  "Kuruhini Chetty",
  "Kurumans",
  "Kurumba",
  "Kurumba Goundar",
  "Kurumbas",
  "Labbais",
  "Lambadi",
  "Latin Catholic Christian Vannar",
  "Latin Catholic Vannar",
  "Latin Catholics",
  "Lingayat (Jangama)",
  "M.B.C.",
  "Madari",
  "Madiga",
  "Maha Malasar",
  "Mahendra / Medara",
  "Mahratta",
  "Maila",
  "Mala",
  "Malai Arayan",
  "Malai Pandaram",
  "Malai Vedan",
  "Malakkuravan",
  "Malasar",
  "Malayakandi",
  "Malayali",
  "Malayamar",
  "Malayar",
  "Male",
  "Mangala",
  "Maniagar",
  "Manigaicar",
  "Mannan",
  "Mapilla",
  "Marakayar",
  "Maravar",
  "Maravars",
  "Maruthuvar",
  "Mavilan",
  "Meenavar",
  "Melakudi",
  "Moger",
  "Mond Golla",
  "Monda Golla",
  "Monda Koravars",
  "Moondrumandai Enbathunalu",
  "Moopanar",
  "Mooppan",
  "Mooppar",
  "Moundadan Chetty",
  "Muchi",
  "Muddim",
  "Mudugar",
  "Muduvan",
  "Mukayar",
  "Mukkulathor",
  "Mukkuvar / Mukayar",
  "Munaliar",
  "Mundala",
  "Muslim / Sayd",
  "Mutharaiyar",
  "Muthuracha",
  "Muthuraja",
  "Muthuvan",
  "Mutlakampatti",
  "Muttiriyar",
  "Nadar",
  "Nagaram",
  "Naidu",
  "Naikkar",
  "Nainar",
  "Nalakeyava",
  "Nanda",
  "Nangudi Vellalar",
  "Nanjil Mudali",
  "Narikoravar (Kuruvikars)",
  "Navithar",
  "Nawalpeta Korachas",
  "Nayadi",
  "Nayar",
  "Nellorepet Oddars",
  "Nil",
  "Nokkar",
  "Nokkars",
  "Nulayar",
  "O.P.S. Vellalar",
  "Odar",
  "Oddars",
  "Odiya",
  "Okkaliga Gowda",
  "Okkaligar",
  "Okkaliya Gowda",
  "Okkaliya-Gowder",
  "Okkaliya-Gowda",
  "Omitted",
  "Oorudaya Gounder",
  "Oottruvalanattu Vellalar",
  "Orudaya Gounder",
  "Others",
  "Ovachar",
  "Padaiachi",
  "Padanna",
  "Padannan",
  "Padayachi",
  "Padaychi",
  "Padmasaliyar",
  "Pagadai",
  "Paidi",
  "Paingam",
  "Paiyur Kotta Vellalar",
  "Pallai",
  "Pallan",
  "Pallayan",
  "Palliyan",
  "Palliyar",
  "Pambada",
  "Pamulu",
  "Panan",
  "Panar",
  "Panchama",
  "Pandiya Vellalar",
  "Panisaivan / Panisivan",
  "Paniyan",
  "Pannadi",
  "Pannayar",
  "Panniandi",
  "Pannirandam Chettiar",
  "Pano",
  "Pantaram",
  "Paraiyan",
  "Paraiyar",
  "Paravan",
  "Paravar",
  "Parayan",
  "Parkavakulam",
  "Parmyiar",
  "Pathiyan",
  "Patnulkarar",
  "Pattariyar",
  "Pattusaliyar",
  "Pedda Boyas",
  "Perike",
  "Perike Balija",
  "Periya Suriyur Kallars",
  "Perumkollar",
  "Pillai",
  "Pillaimor",
  "Piramalai Kallar",
  "Piramalai Kallars",
  "Podikara Vellalar",
  "Pollar",
  "Ponnai Koravars",
  "Pooluva Gounder",
  "Pooluvar",
  "Poraya",
  "PR / SC",
  "Pronopakari",
  "Pulavar",
  "Pulayan",
  "Pulluvan",
  "Pulluvar",
  "Punnan Vettuva Gounder",
  "Pusala",
  "Puthirai Vannan",
  "Raneyar",
  "Reddy",
  "Rowthar",
  "S.C.",
  "Sachiyar",
  "Sadhu Chetty",
  "Sagara",
  "Sakkaraithamadai Koravars",
  "Sakkaravar",
  "Salem Melnad Koravars",
  "Salem Uppu Koravars",
  "Salivagana",
  "Saliyar",
  "Samagara",
  "Samban",
  "Sambavar",
  "Sapari",
  "Saranga Palli Koravars",
  "Sathatha Srivaishnava",
  "Savalakkarar",
  "SC / PL",
  "Schedule Caste",
  "Schtlear",
  "Sedar",
  "Sembanad Maravars",
  "Semman",
  "Senaikudiyar",
  "Senaithalaivar",
  "Sengunthar",
  "Serakula Vellalar",
  "Serva",
  "Servai",
  "Settipalli Koravars",
  "Shanar",
  "Sheik",
  "Sholaga",
  "Sidhanar",
  "Sooramari Oddars",
  "Sourashtra",
  "Sowrstra",
  "Sozha Vellalar",
  "Sozhia Chetty",
  "Sozhia Vellalar",
  "Srisayar",
  "ST",
  "Sundaram Chetty",
  "Surithimar Nathamar",
  "Syed",
  "Telikula",
  "Telugupatty Chetty",
  "Telungapatti Chettis",
  "Thalli Koravars",
  "Thandan",
  "Thevar",
  "Thogamalai Koravars",
  "Thogatta Veerakshatriya",
  "Tholkollar",
  "Tholuva Naicker",
  "Thondaman",
  "Thoraiyar",
  "Thoriyar",
  "Thoti",
  "Thottia Naicker",
  "Thottia Naickers",
  "Thozhu",
  "Thuluva Vellala",
  "Tiruvalluvar",
  "Toda",
  "Ukkirakula Kshatriya Naicker",
  "Umblar",
  "Uppara",
  "Uppillia",
  "Uppukoravars",
  "Urali Gounder",
  "Urali Gounders",
  "Uraly",
  "Urikkara Nayakkar",
  "Uthama Chettiar",
  "Vaduga Ayar",
  "Vaduga Idaiyar",
  "Vadugar",
  "Vaduvarpatti Koravars",
  "Vakkaligar",
  "Valaiyar",
  "Valayars",
  "Vallalam",
  "Vallambar",
  "Vallanattu Chettiar",
  "Vallon",
  "Valluvan",
  "Valmiki",
  "Van Nair",
  "Vania Chettiar",
  "Vaniyar",
  "Vannan",
  "Vannar",
  "Vanniakula Kshatriya",
  "Varaganeri Koravars",
  "Vathiriyan",
  "Vedar",
  "Veduvar",
  "Veerasaiva",
  "Velakatalanair",
  "Velakattalavar",
  "Velalar",
  "Velan",
  "Velar",
  "Vellan Chettiar",
  "Vellar",
  "Veluthodathu Nair",
  "Venganur Adi-Dravidar",
  "Veppur Parayan",
  "Vetalakara Naicker",
  "Vetan",
  "Vetrilaikarar",
  "Vetta Koravars",
  "Vettaikarar",
  "Vettiyan",
  "Vettuva Gounder",
  "Vettuvan",
  "Virakodi Vellala",
  "Viswakarma",
  "Viswakarmala",
  "Vokkaligar",
  "Wayalpad",
  "Wynad Chetty",
  "Yadhava",
  "Yadav",
  "Yavana",
  "Yerukula",
  "Yogeeswarar",
].sort((a, b) => a.localeCompare(b));
