/**
 * Full list of country dialing codes for the phone input.
 * India is pinned first (primary audience); the rest are alphabetical by country.
 * label format: "<flag> <code>  <Country>"
 */
export type CountryCode = { code: string; label: string; name: string };

export const COUNTRY_CODES: CountryCode[] = [
  { name: "India", code: "+91", label: "🇮🇳 +91  India" },

  { name: "Afghanistan", code: "+93", label: "🇦🇫 +93  Afghanistan" },
  { name: "Albania", code: "+355", label: "🇦🇱 +355  Albania" },
  { name: "Algeria", code: "+213", label: "🇩🇿 +213  Algeria" },
  { name: "Andorra", code: "+376", label: "🇦🇩 +376  Andorra" },
  { name: "Angola", code: "+244", label: "🇦🇴 +244  Angola" },
  { name: "Argentina", code: "+54", label: "🇦🇷 +54  Argentina" },
  { name: "Armenia", code: "+374", label: "🇦🇲 +374  Armenia" },
  { name: "Australia", code: "+61", label: "🇦🇺 +61  Australia" },
  { name: "Austria", code: "+43", label: "🇦🇹 +43  Austria" },
  { name: "Azerbaijan", code: "+994", label: "🇦🇿 +994  Azerbaijan" },
  { name: "Bahrain", code: "+973", label: "🇧🇭 +973  Bahrain" },
  { name: "Bangladesh", code: "+880", label: "🇧🇩 +880  Bangladesh" },
  { name: "Belarus", code: "+375", label: "🇧🇾 +375  Belarus" },
  { name: "Belgium", code: "+32", label: "🇧🇪 +32  Belgium" },
  { name: "Belize", code: "+501", label: "🇧🇿 +501  Belize" },
  { name: "Benin", code: "+229", label: "🇧🇯 +229  Benin" },
  { name: "Bhutan", code: "+975", label: "🇧🇹 +975  Bhutan" },
  { name: "Bolivia", code: "+591", label: "🇧🇴 +591  Bolivia" },
  { name: "Bosnia and Herzegovina", code: "+387", label: "🇧🇦 +387  Bosnia and Herzegovina" },
  { name: "Botswana", code: "+267", label: "🇧🇼 +267  Botswana" },
  { name: "Brazil", code: "+55", label: "🇧🇷 +55  Brazil" },
  { name: "Brunei", code: "+673", label: "🇧🇳 +673  Brunei" },
  { name: "Bulgaria", code: "+359", label: "🇧🇬 +359  Bulgaria" },
  { name: "Burkina Faso", code: "+226", label: "🇧🇫 +226  Burkina Faso" },
  { name: "Burundi", code: "+257", label: "🇧🇮 +257  Burundi" },
  { name: "Cambodia", code: "+855", label: "🇰🇭 +855  Cambodia" },
  { name: "Cameroon", code: "+237", label: "🇨🇲 +237  Cameroon" },
  { name: "Canada", code: "+1", label: "🇨🇦 +1  Canada" },
  { name: "Cape Verde", code: "+238", label: "🇨🇻 +238  Cape Verde" },
  { name: "Central African Republic", code: "+236", label: "🇨🇫 +236  Central African Republic" },
  { name: "Chad", code: "+235", label: "🇹🇩 +235  Chad" },
  { name: "Chile", code: "+56", label: "🇨🇱 +56  Chile" },
  { name: "China", code: "+86", label: "🇨🇳 +86  China" },
  { name: "Colombia", code: "+57", label: "🇨🇴 +57  Colombia" },
  { name: "Comoros", code: "+269", label: "🇰🇲 +269  Comoros" },
  { name: "Congo (DRC)", code: "+243", label: "🇨🇩 +243  Congo (DRC)" },
  { name: "Congo (Republic)", code: "+242", label: "🇨🇬 +242  Congo (Republic)" },
  { name: "Costa Rica", code: "+506", label: "🇨🇷 +506  Costa Rica" },
  { name: "Croatia", code: "+385", label: "🇭🇷 +385  Croatia" },
  { name: "Cuba", code: "+53", label: "🇨🇺 +53  Cuba" },
  { name: "Cyprus", code: "+357", label: "🇨🇾 +357  Cyprus" },
  { name: "Czech Republic", code: "+420", label: "🇨🇿 +420  Czech Republic" },
  { name: "Denmark", code: "+45", label: "🇩🇰 +45  Denmark" },
  { name: "Djibouti", code: "+253", label: "🇩🇯 +253  Djibouti" },
  { name: "Dominican Republic", code: "+1809", label: "🇩🇴 +1809  Dominican Republic" },
  { name: "Ecuador", code: "+593", label: "🇪🇨 +593  Ecuador" },
  { name: "Egypt", code: "+20", label: "🇪🇬 +20  Egypt" },
  { name: "El Salvador", code: "+503", label: "🇸🇻 +503  El Salvador" },
  { name: "Estonia", code: "+372", label: "🇪🇪 +372  Estonia" },
  { name: "Eswatini", code: "+268", label: "🇸🇿 +268  Eswatini" },
  { name: "Ethiopia", code: "+251", label: "🇪🇹 +251  Ethiopia" },
  { name: "Fiji", code: "+679", label: "🇫🇯 +679  Fiji" },
  { name: "Finland", code: "+358", label: "🇫🇮 +358  Finland" },
  { name: "France", code: "+33", label: "🇫🇷 +33  France" },
  { name: "Gabon", code: "+241", label: "🇬🇦 +241  Gabon" },
  { name: "Gambia", code: "+220", label: "🇬🇲 +220  Gambia" },
  { name: "Georgia", code: "+995", label: "🇬🇪 +995  Georgia" },
  { name: "Germany", code: "+49", label: "🇩🇪 +49  Germany" },
  { name: "Ghana", code: "+233", label: "🇬🇭 +233  Ghana" },
  { name: "Greece", code: "+30", label: "🇬🇷 +30  Greece" },
  { name: "Guatemala", code: "+502", label: "🇬🇹 +502  Guatemala" },
  { name: "Guinea", code: "+224", label: "🇬🇳 +224  Guinea" },
  { name: "Guyana", code: "+592", label: "🇬🇾 +592  Guyana" },
  { name: "Haiti", code: "+509", label: "🇭🇹 +509  Haiti" },
  { name: "Honduras", code: "+504", label: "🇭🇳 +504  Honduras" },
  { name: "Hong Kong", code: "+852", label: "🇭🇰 +852  Hong Kong" },
  { name: "Hungary", code: "+36", label: "🇭🇺 +36  Hungary" },
  { name: "Iceland", code: "+354", label: "🇮🇸 +354  Iceland" },
  { name: "Indonesia", code: "+62", label: "🇮🇩 +62  Indonesia" },
  { name: "Iran", code: "+98", label: "🇮🇷 +98  Iran" },
  { name: "Iraq", code: "+964", label: "🇮🇶 +964  Iraq" },
  { name: "Ireland", code: "+353", label: "🇮🇪 +353  Ireland" },
  { name: "Israel", code: "+972", label: "🇮🇱 +972  Israel" },
  { name: "Italy", code: "+39", label: "🇮🇹 +39  Italy" },
  { name: "Ivory Coast", code: "+225", label: "🇨🇮 +225  Ivory Coast" },
  { name: "Jamaica", code: "+1876", label: "🇯🇲 +1876  Jamaica" },
  { name: "Japan", code: "+81", label: "🇯🇵 +81  Japan" },
  { name: "Jordan", code: "+962", label: "🇯🇴 +962  Jordan" },
  { name: "Kazakhstan", code: "+7", label: "🇰🇿 +7  Kazakhstan" },
  { name: "Kenya", code: "+254", label: "🇰🇪 +254  Kenya" },
  { name: "Kuwait", code: "+965", label: "🇰🇼 +965  Kuwait" },
  { name: "Kyrgyzstan", code: "+996", label: "🇰🇬 +996  Kyrgyzstan" },
  { name: "Laos", code: "+856", label: "🇱🇦 +856  Laos" },
  { name: "Latvia", code: "+371", label: "🇱🇻 +371  Latvia" },
  { name: "Lebanon", code: "+961", label: "🇱🇧 +961  Lebanon" },
  { name: "Lesotho", code: "+266", label: "🇱🇸 +266  Lesotho" },
  { name: "Liberia", code: "+231", label: "🇱🇷 +231  Liberia" },
  { name: "Libya", code: "+218", label: "🇱🇾 +218  Libya" },
  { name: "Liechtenstein", code: "+423", label: "🇱🇮 +423  Liechtenstein" },
  { name: "Lithuania", code: "+370", label: "🇱🇹 +370  Lithuania" },
  { name: "Luxembourg", code: "+352", label: "🇱🇺 +352  Luxembourg" },
  { name: "Macau", code: "+853", label: "🇲🇴 +853  Macau" },
  { name: "Madagascar", code: "+261", label: "🇲🇬 +261  Madagascar" },
  { name: "Malawi", code: "+265", label: "🇲🇼 +265  Malawi" },
  { name: "Malaysia", code: "+60", label: "🇲🇾 +60  Malaysia" },
  { name: "Maldives", code: "+960", label: "🇲🇻 +960  Maldives" },
  { name: "Mali", code: "+223", label: "🇲🇱 +223  Mali" },
  { name: "Malta", code: "+356", label: "🇲🇹 +356  Malta" },
  { name: "Mauritania", code: "+222", label: "🇲🇷 +222  Mauritania" },
  { name: "Mauritius", code: "+230", label: "🇲🇺 +230  Mauritius" },
  { name: "Mexico", code: "+52", label: "🇲🇽 +52  Mexico" },
  { name: "Moldova", code: "+373", label: "🇲🇩 +373  Moldova" },
  { name: "Monaco", code: "+377", label: "🇲🇨 +377  Monaco" },
  { name: "Mongolia", code: "+976", label: "🇲🇳 +976  Mongolia" },
  { name: "Montenegro", code: "+382", label: "🇲🇪 +382  Montenegro" },
  { name: "Morocco", code: "+212", label: "🇲🇦 +212  Morocco" },
  { name: "Mozambique", code: "+258", label: "🇲🇿 +258  Mozambique" },
  { name: "Myanmar", code: "+95", label: "🇲🇲 +95  Myanmar" },
  { name: "Namibia", code: "+264", label: "🇳🇦 +264  Namibia" },
  { name: "Nepal", code: "+977", label: "🇳🇵 +977  Nepal" },
  { name: "Netherlands", code: "+31", label: "🇳🇱 +31  Netherlands" },
  { name: "New Zealand", code: "+64", label: "🇳🇿 +64  New Zealand" },
  { name: "Nicaragua", code: "+505", label: "🇳🇮 +505  Nicaragua" },
  { name: "Niger", code: "+227", label: "🇳🇪 +227  Niger" },
  { name: "Nigeria", code: "+234", label: "🇳🇬 +234  Nigeria" },
  { name: "North Macedonia", code: "+389", label: "🇲🇰 +389  North Macedonia" },
  { name: "Norway", code: "+47", label: "🇳🇴 +47  Norway" },
  { name: "Oman", code: "+968", label: "🇴🇲 +968  Oman" },
  { name: "Pakistan", code: "+92", label: "🇵🇰 +92  Pakistan" },
  { name: "Palestine", code: "+970", label: "🇵🇸 +970  Palestine" },
  { name: "Panama", code: "+507", label: "🇵🇦 +507  Panama" },
  { name: "Papua New Guinea", code: "+675", label: "🇵🇬 +675  Papua New Guinea" },
  { name: "Paraguay", code: "+595", label: "🇵🇾 +595  Paraguay" },
  { name: "Peru", code: "+51", label: "🇵🇪 +51  Peru" },
  { name: "Philippines", code: "+63", label: "🇵🇭 +63  Philippines" },
  { name: "Poland", code: "+48", label: "🇵🇱 +48  Poland" },
  { name: "Portugal", code: "+351", label: "🇵🇹 +351  Portugal" },
  { name: "Qatar", code: "+974", label: "🇶🇦 +974  Qatar" },
  { name: "Romania", code: "+40", label: "🇷🇴 +40  Romania" },
  { name: "Russia", code: "+7", label: "🇷🇺 +7  Russia" },
  { name: "Rwanda", code: "+250", label: "🇷🇼 +250  Rwanda" },
  { name: "Saudi Arabia", code: "+966", label: "🇸🇦 +966  Saudi Arabia" },
  { name: "Senegal", code: "+221", label: "🇸🇳 +221  Senegal" },
  { name: "Serbia", code: "+381", label: "🇷🇸 +381  Serbia" },
  { name: "Seychelles", code: "+248", label: "🇸🇨 +248  Seychelles" },
  { name: "Sierra Leone", code: "+232", label: "🇸🇱 +232  Sierra Leone" },
  { name: "Singapore", code: "+65", label: "🇸🇬 +65  Singapore" },
  { name: "Slovakia", code: "+421", label: "🇸🇰 +421  Slovakia" },
  { name: "Slovenia", code: "+386", label: "🇸🇮 +386  Slovenia" },
  { name: "Somalia", code: "+252", label: "🇸🇴 +252  Somalia" },
  { name: "South Africa", code: "+27", label: "🇿🇦 +27  South Africa" },
  { name: "South Korea", code: "+82", label: "🇰🇷 +82  South Korea" },
  { name: "South Sudan", code: "+211", label: "🇸🇸 +211  South Sudan" },
  { name: "Spain", code: "+34", label: "🇪🇸 +34  Spain" },
  { name: "Sri Lanka", code: "+94", label: "🇱🇰 +94  Sri Lanka" },
  { name: "Sudan", code: "+249", label: "🇸🇩 +249  Sudan" },
  { name: "Sweden", code: "+46", label: "🇸🇪 +46  Sweden" },
  { name: "Switzerland", code: "+41", label: "🇨🇭 +41  Switzerland" },
  { name: "Syria", code: "+963", label: "🇸🇾 +963  Syria" },
  { name: "Taiwan", code: "+886", label: "🇹🇼 +886  Taiwan" },
  { name: "Tajikistan", code: "+992", label: "🇹🇯 +992  Tajikistan" },
  { name: "Tanzania", code: "+255", label: "🇹🇿 +255  Tanzania" },
  { name: "Thailand", code: "+66", label: "🇹🇭 +66  Thailand" },
  { name: "Togo", code: "+228", label: "🇹🇬 +228  Togo" },
  { name: "Trinidad and Tobago", code: "+1868", label: "🇹🇹 +1868  Trinidad and Tobago" },
  { name: "Tunisia", code: "+216", label: "🇹🇳 +216  Tunisia" },
  { name: "Turkey", code: "+90", label: "🇹🇷 +90  Turkey" },
  { name: "Turkmenistan", code: "+993", label: "🇹🇲 +993  Turkmenistan" },
  { name: "Uganda", code: "+256", label: "🇺🇬 +256  Uganda" },
  { name: "Ukraine", code: "+380", label: "🇺🇦 +380  Ukraine" },
  { name: "United Arab Emirates", code: "+971", label: "🇦🇪 +971  United Arab Emirates" },
  { name: "United Kingdom", code: "+44", label: "🇬🇧 +44  United Kingdom" },
  { name: "United States", code: "+1", label: "🇺🇸 +1  United States" },
  { name: "Uruguay", code: "+598", label: "🇺🇾 +598  Uruguay" },
  { name: "Uzbekistan", code: "+998", label: "🇺🇿 +998  Uzbekistan" },
  { name: "Venezuela", code: "+58", label: "🇻🇪 +58  Venezuela" },
  { name: "Vietnam", code: "+84", label: "🇻🇳 +84  Vietnam" },
  { name: "Yemen", code: "+967", label: "🇾🇪 +967  Yemen" },
  { name: "Zambia", code: "+260", label: "🇿🇲 +260  Zambia" },
  { name: "Zimbabwe", code: "+263", label: "🇿🇼 +263  Zimbabwe" },
];

// Dial codes sorted longest-first, for correct prefix matching when parsing a
// stored value like "+1868..." (Trinidad) vs "+1..." (US/Canada).
export const CODES_BY_LENGTH = [...COUNTRY_CODES]
  .map((c) => c.code)
  .sort((a, b) => b.length - a.length);
